# version: "3"

# services:
#   client:
#     build:
#       context: ./client
#     ports:
#       - "3000:3000"

#   server:
#     build:
#       context: ./server
#     ports:
#       - "3001:3001"
#     depends_on:
#       - redis
#     env_file:
#       - .env

#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"

# version: "3"

# services:
#   client:
#     build:
#       context: ./client
#     ports:
#       - "3000:3000"

#   server:
#     build:
#       context: ./server
#     ports:
#       - "3001:3001"
#     depends_on:
#       - redis
#     env_file:
#       - .env

#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"

version: "3"

services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
